ALTER TABLE parents ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE parents ADD COLUMN IF NOT EXISTS verification_token_hash TEXT;
ALTER TABLE parents ADD COLUMN IF NOT EXISTS verification_expires_at TIMESTAMPTZ;

ALTER TABLE students ADD COLUMN IF NOT EXISTS parent_id INTEGER REFERENCES parents(id);
